#数据库连接配置
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #postgresql不同通过createDatabaseIfNotExist=true创建数据库,mysql可以创建数据库
    url: jdbc:postgresql://localhost:5432/flowable?characterEncoding=utf8
    username: postgres
    password: root
#注意流程图的xml需要放在resources的processes文件夹下,没有需要创建
server:
  port: 8082